### ISSUE TITLE
Javascript Processing

### ISSUE THREAD

**Issue by pjpreilly** [parrotgeek1/FirefoxLegacy#9] opened 2020-12-04 22:21 UTC
Go **[here](https://www.wunderground.com/forecast/us/pa/cheltenham/40.05,-75.11)** and click on "CHANGE" notice the javascript processing bind the browser. This is the current Lion version on a macbook 4,1

![Screenshot 2020-12-04 at 5 18 31 PM](https://user-images.githubusercontent.com/10430084/101221136-148f7c80-3655-11eb-9021-a634bf52ef9e.png)

**Comment by parrotgeek1** [comment] 2020-12-15 23:04
I can't reproduce this on 71.0p2 on patched 10.8.5, iMac5,1. What version
and os are you using?

-- 
Ethan Nelson-Moore

**Comment by pjpreilly** [comment] 2020-12-16 00:09
68.12.p2 on Lion 10.7.5 with macbooks 3,1 & 4,1. Cloudready chromium os on this hardware javascript decoding runs fine on this page with this hardware. Also Waterfox Classic (osx fix) has issues processing javascript on this site too.

**Comment by parrotgeek1** [comment] 2021-01-02 21:35
It works on official 68.12esr (Big Sur), although the page seems very slow to load when clicking Change. Is that what you mean? I will test 68.12.0p2 on 10.8.5 asap; I don't have access to 10.7.5 right now.

**Comment by pjpreilly** [comment] 2021-01-02 21:50
Yeah it's that CHANGE click that seems to freeze it up....

**Comment by pjpreilly** [comment] 2021-01-22 19:21
I saw some commits for speed fixes.. a new release coming anytime soon?  I'll test if you need a tester on 10.7

**Comment by parrotgeek1** [comment] 2021-01-22 19:24
Those are speed fixes to a script I used to aid in the testing of Firefox
Legacy. They are not fixes to the speed of the browser itself.

**Comment by parrotgeek1** [comment] 2021-01-25 00:08
This appears to be fixed in the latest version 68.12.0p3, which implements a large number of newer web APIs.

**Closed by parrotgeek1** 2021-01-25 00:08 UTC
