### ISSUE TITLE
Firefox Legacy 68 crashes 

### ISSUE THREAD

**Issue by scrutinizer11** [parrotgeek1/FirefoxLegacy#6] opened 2020-08-29 18:14 UTC
Hello,
I just downloaded FF Legacy 68 on 10.7 and it crashes on launch: launched 2 times. The first time, it opened to its default profile (not mine) and displayed an informational pop-up, the second one it just crashed. I still have the previous one, 67, left in place, out of prudence, and have put 68 in other location rather than replacing the old one. The crash log is attached. Thank you for your efforts.
[crashreporter_2020-08-29-210214.txt](https://github.com/parrotgeek1/FirefoxLegacy/files/5145808/crashreporter_2020-08-29-210214.txt)

**Comment by parrotgeek1** [comment] 2020-08-29 19:31
What computer do you have? I can't reproduce this on a 2006 iMac (5,1) nor a 2009 iMac.

**Comment by scrutinizer11** [comment] 2020-08-29 19:36
MacBook Pro mid2012 (9.1)

**Comment by parrotgeek1** [comment] 2020-08-29 19:37
Strange. I'll investigate this and in the meantime I'll put 67 back on the site.

**Comment by pjpreilly** [comment] 2020-08-29 20:30
@scrutinizer11 is that 10.7.5?

**Comment by scrutinizer11** [comment] 2020-08-29 22:09
Yes, 10.7.5 Server

**Comment by parrotgeek1** [comment] 2020-08-29 22:27
I don't know why this is happening, but I put 67.0.4 back on the website while I investigate.

**Comment by scrutinizer11** [comment] 2020-08-29 22:37
No prob.

**Comment by pjpreilly** [comment] 2020-08-29 22:57
Dumb question but I must...
Are you sure you didn't grab v71 meant for Mountain Lion 10.8.5?

**Comment by parrotgeek1** [comment] 2020-08-30 00:25
@pjpreilly this shouldn't be possible because the minimum version is set to 10.8 on that so it would show 🚫

**Comment by pjpreilly** [comment] 2020-08-30 00:48
@parrotgeek1 ... yup it's as you said...

**Comment by pjpreilly** [comment] 2020-08-30 00:53
Maybe graphics:

*This system has dual graphics processors -- a NVIDIA GeForce GT 650M with 512 MB of dedicated GDDR5 SDRAM and Intel HD Graphics 4000 with memory shared with the system.

**Comment by pjpreilly** [comment] 2020-08-30 00:56
and.....

This model is compatible with the final version of macOS Mojave (10.14) and the final version of macOS Catalina (10.15), as well. It does not support macOS Big Sur (macOS 11) or later versions of the macOS.

**Comment by pjpreilly** [comment] 2020-09-08 03:33
Are there any updates to this issue? I'm using it on a macbook 3,1 & 4,1 with only a few already known issues. No launching or crashing issues though.

**Comment by parrotgeek1** [comment] 2020-09-08 03:35
I am baffled by this issue and might just try to bisect what change in my build script caused it by building 68 with the 67 scripts

**Comment by parrotgeek1** [comment] 2020-09-12 02:44
This issue has been fixed in 68.12.0p2 released just now; it was actually caused by a missing function in 10.7 which Firefox started using in 68.3 ESR.

**Closed by parrotgeek1** 2020-09-12 02:44 UTC

**Comment by parrotgeek1** [comment] 2020-09-12 02:47
@pjpreilly ping

**Comment by pjpreilly** [comment] 2020-09-12 02:54
Nice!

**Comment by parrotgeek1** [comment] 2020-09-12 03:05
I also now have access to my macbook4,1 (it was stuck at school after they sent me home in march for covid) which means that I am now able to test things on 10.7 before releasing them

**Comment by pjpreilly** [comment] 2020-09-12 03:31
Cool, maybe you could look at the display issue on google calendar month view where the previous month & next month icon are not rendered correctly. It's probably related to the icon issue on google news media play icon overlay ( a bur under my saddle). And then there's the DRM Widevine plugin crash...... TIA...

**Comment by scrutinizer11** [comment] 2020-09-12 04:08
Thank you, very much!
